Week2E
micaylamendoza/my-portfolio pull request #9
Opened 2020-06-18 05:42 UTC by micaylamendoza

Implemented Datastore to permanently store my comments

2020-06-18 15:51 UTC, classm-sps requested changes
In addition to addressing the other comments I've made, please merge week2D and pull to incorporate those changes into this PR.

2020-06-18 15:51 UTC, classm-sps commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  ArrayList<String> comments = new ArrayList<>();
so one of goals of using the datastore is to avoid having to store comments in the server's memory. Let's remove this.

2020-06-18 15:51 UTC, classm-sps commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    for (Entity entity : results.asIterable());
Querying the datastore should go into doGet(). But also notice that the for loop here (line 76) isn't doing anything with the data returned from datastore.

2020-06-18 21:00 UTC, classm-sps commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  ArrayList<String> comments = new ArrayList<>();
Hmmm, not sure why this comment was resolved, given that the local array is still here...

2020-06-22 17:15 UTC, classm-sps approved these changes
Please just fix the content type in the doGet response, then this is fine to merge. Great job!

2020-06-22 17:15 UTC, classm-sps commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    response.setContentType("text/html");
This should be application/json still

2020-06-24 05:38 UTC, micaylamendoza commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    response.setContentType("text/html");
Got it

2020-06-24 05:41 UTC, merged